#!/bin/sh
# shellcheck disable=1090,2154

notif_identifier="i3b$(echo "$0" | tr '/' '\n' | tail -1)"
notif="notify-send -h string:x-canonical-private-synchronous:$notif_identifier"

if [ -e "${XDG_CACHE_HOME-$HOME/.cache}/wal/colors.sh" ]; then
    . "${XDG_CACHE_HOME-$HOME/.cache}/wal/colors.sh"
    # blockcolor=$color6
    # txtcolor=$color0
    blockcolor=$color8
    txtcolor=$color15
else
    blockcolor="#689d6a"
    txtcolor="#282828"
fi

LOCATION_LIST="${XDG_CONFIG_HOME-$HOME/.config}/i3blocks/accuweather"
TEMPERATURE_UNIT="${XDG_CONFIG_HOME-$HOME/.config}/i3blocks/accuweather-unit"
[ ! -e "$TEMPERATURE_UNIT" ] && {
    { echo "$LANG" | grep US && echo "u" >"$TEMPERATURE_UNIT"; } ||
        echo "m" >"$TEMPERATURE_UNIT"
}

get_current_weather()
{
    current_location=$(head -1 "$LOCATION_LIST")

    unit=$(cat "$TEMPERATURE_UNIT")
    wttr_unit="$unit"
    accuweather_unit=$([ "$unit" = u ] && echo 0 || echo 1)

    unit=$(cat "$TEMPERATURE_UNIT")
    wttr_unit="$unit"
    accuweather_unit=$([ "$unit" = u ] && echo 0 || echo 1)

    current_location=$(head -1 "$LOCATION_LIST")

    ping -c 1 1.1.1.1 >/dev/null || { icon="X" && exit 1; }

    curl -s "http://rss.accuweather.com/rss/liveweather_rss.asp?metric=$accuweather_unit&locCode=$current_location" |
            grep "Currently" >/tmp/weather

    current_location_name=$(awk -F':' '/in/{print $1}' /tmp/weather |
            awk -F'in' '{print $2}' | xargs)

    location_name_spaces_converted=$(echo "$current_location_name" | tr ' ' '+')
}

get_current_weather

case $BLOCK_BUTTON in
1) # Left Click
    $notif "$(curl "wttr.in/$location_name_spaces_converted?0&T&Q$wttr_unit")"
    ;;
2) # Middle Click
    { [ "$(cat "$TEMPERATURE_UNIT")" = u ] &&
        echo m >"$TEMPERATURE_UNIT"; } || echo u >"$TEMPERATURE_UNIT"
    ;;
3) # Right Click
    # $TERMINAL --class=float -d 125 41 --hold -e \
    # curl "wttr.in/$current_location?$wttr_unit"
    $TERMINAL --class=float --hold -e \
        curl "wttr.in/$location_name_spaces_converted?$wttr_unit"
    ;;
4) # Scroll Up
    moved_location=$(head -1 "$LOCATION_LIST")
    other_locations=$(tail -n +2 "$LOCATION_LIST")
    echo "$other_locations" >"$LOCATION_LIST"
    echo "$moved_location" >>"$LOCATION_LIST"
    get_current_weather
    ;;
5) # Scroll Down
    next_location=$(tail -1 "$LOCATION_LIST")
    other_locations=$(head -n -1 "$LOCATION_LIST")
    echo "$next_location" >"$LOCATION_LIST"
    echo "$other_locations" >>"$LOCATION_LIST"
    get_current_weather
    ;;
esac

current_weather=$(awk -F':' '/Currently:/{print $2}' /tmp/weather | xargs)

full_temperature=$(awk -F':' '/Currently:/{print $3}' /tmp/weather | xargs |
    sed 's/F/°F/;s/C/°C/;s|</title>||')

temperature=$(echo "$full_temperature" | awk -F° '{print $1}')
temperature_unit=$(echo "$full_temperature" | awk -F° '{print $2}')

if [ "$temperature_unit" = F ]; then
    if [ "$temperature" -ge 95 ]; then
        # Red
        temp_color="#ff0000"
    elif [ "$temperature" -ge 85 ]; then
        # Orange
        temp_color="#ff8800"
    elif [ "$temperature" -ge 75 ]; then
        # Yellow
        temp_color="#ffff00"
    elif [ "$temperature" -ge 65 ]; then
        # Green
        temp_color="#00ff00"
    elif [ "$temperature" -ge 55 ]; then
        # Light blue
        temp_color="#0088ff"
    elif [ "$temperature" -ge 45 ]; then
        # Blue
        temp_color="#0000ff"
    else
        # Purple
        temp_color="#8800ff"
    fi
fi

case $current_weather in
"Sunny") icon='' ;;
"Partly Sunny") icon='' ;;
"Mostly Sunny") icon=' ' ;;
"Intermittent Clouds") icon='' ;;
"Hazy Sunshine") icon='' ;;
"Hazy Moonlight") icon='' ;;
"Hot") icon='' ;;
"Clear") icon='' ;;
"Mostly Clear") icon='' ;;
"Mostly Clear w/ Flurries") icon='' ;;
"Flurries") icon='' ;;
"Sleet") icon='' ;;
"Ice") icon='' ;;
"Windy") icon='' ;;
"Partly Cloudy") icon='' ;;
"Mostly Cloudy") icon='' ;;
"Mostly Cloudy w/ Showers") icon='' ;;
"Partly Cloudy w/ Showers") icon='' ;;
"T-Storms") icon='' ;;
"Thunderstorms") icon=' ' ;;
"Mostly Cloudy w/ T-Storms") icon=' ' ;;
"Mostly Cloudy w/ Snow") icon=' ' ;;
"Snow") icon='' ;;
"Rain and Snow") icon=' ' ;;
"Partly Cloudy w/ T-Storms") icon='' ;;
"Rain") icon='' ;;
"Dreary (Overcast)") icon='' ;;
"Cloudy") icon='' ;;
"Fog") icon='' ;;
"Showers") icon='' ;;
*) icon="$current_weather" ;;
esac

if [ -t 0 ]; then
    echo "$icon $temperature $current_location_name"
else
    printf "<b><span foreground='%s' background='%s'></span>" \
    	"$blockcolor" "$color0"
    printf "<span foreground='%s' background='%s'> %s </span>" \
    	"$temp_color" "$blockcolor" "$icon"
    printf "<span foreground='%s' background='%s'>%s</span>" \
    	"$temp_color" "$blockcolor" "$full_temperature"
    printf "<span foreground='%s' background='%s'> %s </span>" \
    	"$txtcolor" "$blockcolor" "$current_location_name"
    printf "<span foreground='%s' background='%s'></span></b>\n" \
    	"$color0" "$blockcolor"
fi
