#!/bin/sh
# shellcheck disable=1090,2154

LOCATION_LIST="${XDG_CONFIG_HOME:-$HOME/.config}/i3blocks/accuweather"
. "${XDG_CACHE_HOME:-$HOME/.cache}/wal/colors.sh"

blockcolor=$color6
txtcolor=$color0

current_location=$(head -1 "$LOCATION_LIST")

# 0:F
# 1:C
METRIC=0

case $BLOCK_BUTTON in
    1) # Left Click
        notify-send \
            -h string:x-canonical-private-synchronous:i3baccuweather \
            "$(curl "wttr.in/$current_location?0&T&Q")"
        ;;
    2) # Middle Click
        ;;
    3) # Right Click
        $TERMINAL --class=float -d 125 41 --hold -e curl "wttr.in/$current_location"
        ;;
    4) # Scroll Up
        moved_location=$(head -1 "$LOCATION_LIST")
        other_locations=$(tail -n +2 "$LOCATION_LIST")
        echo "$other_locations" > "$LOCATION_LIST"
        echo "$moved_location" >> "$LOCATION_LIST"
        ;;
    5) # Scroll Down
        next_location=$(tail -1 "$LOCATION_LIST")
        other_locations=$(head -n -1 "$LOCATION_LIST")
        echo "$next_location" > "$LOCATION_LIST"
        echo "$other_locations" >> "$LOCATION_LIST"
        ;;
esac

current_location=$(head -1 "$LOCATION_LIST")

ping -c 1 1.1.1.1 >/dev/null || {
    icon="X" && exit 1
}

curl -s "http://rss.accuweather.com/rss/liveweather_rss.asp?metric=$METRIC&locCode=$current_location" |
    grep "Currently" > /tmp/weather

current_location_name=$(
    awk -F':' '/in/{print $1}' /tmp/weather |
    awk -F'in' '{print $2}'  | xargs
)

current_weather=$(
    grep Currently: /tmp/weather |
    awk -F':' '{print $2}' | xargs
)

temperature=$(
    grep Currently: /tmp/weather |
    awk -F':' '{print $3}' | xargs |
    sed 's/F/°F/' | sed 's|</title>||'
)

case $current_weather in
    "Sunny")
        icon=''
        ;;
    "Partly Sunny")
        icon=''
        ;;
    "Mostly Sunny")
        icon=''
        ;;
    "Intermittent Clouds")
        icon=''
        ;;
    "Hazy Sunshine")
        icon=''
        ;;
    "Hazy Moonlight")
        icon=''
        ;;
    "Hot")
        icon=''
        ;;
    "Clear")
        icon=''
        ;;
    "Mostly Clear")
        icon=''
        ;;
    "Mostly Clear w/ Flurries")
        icon=''
        ;;
    "Flurries")
        icon=''
        ;;
    "Windy")
        icon=''
        ;;
    "Partly Cloudy")
        icon=''
        ;;
    "Mostly Cloudy")
        icon=''
        ;;
    "Mostly Cloudy w/ Showers")
        icon=''
        ;;
    "Partly Cloudy w/ Showers")
        icon=''
        ;;
    "T-Storms")
        icon=''
        ;;
    "Thunderstorms")
        icon=''
        ;;
    "Mostly Cloudy w/ T-Storms")
        icon=' '
        ;;
    "Mostly Cloudy w/ Snow")
        icon=''
        ;;
    "Snow")
        icon=''
        ;;
    "Rain and Snow")
        icon=''
        ;;
    "Partly Cloudy w/ T-Storms")
        icon=''
        ;;
    "Rain")
        icon=''
        ;;
    "Dreary (Overcast)")
        icon=''
        ;;
    "Cloudy")
        icon=''
        ;;
    "Fog")
        icon=''
        ;;
    "Showers")
        icon=''
        ;;
    *)
        icon='TO BE IMPLEMENTED'
        ;;
esac

printf "\
<b><span foreground='$blockcolor' background='$color0'></span>\
<span foreground='$txtcolor' background='$blockcolor'> %s</span>\
<span foreground='$color0' background='$blockcolor'></span></b>\n" \
"$icon $temperature $current_location_name "
