#!/bin/sh
# shellcheck disable=1090,2154

. "${XDG_CACHE_HOME-$HOME/.cache}/wal/colors.sh"
blockcolor=$color11
txtcolor=$color8

connected_devices=$(
    for dev in $(bluetoothctl devices | awk '{print $2}'); do
        bluetoothctl info "$dev"
    done | grep -B8 "Connected: yes" | awk '/Device/{print $2}')

btinfo=$(for dev in $connected_devices; do bluetoothctl info "$dev"; done)

if [ -d "/usr/share/icons/HighContrast" ]; then
    notif_icon="/usr/share/icons/HighContrast/256x256/status/bluetooth-active.png"
elif [ -d "/usr/share/icons/Adwaita" ]; then
    notif_icon="/usr/share/icons/Adwaita/96x96/devices/bluetooth-symbolic.symbolic.png"
else
    # TODO: curl a default bluetooth icon.
    true
fi

case $BLOCK_BUTTON in
    1) # Left Click
        bt-select
        ;;
    2) # Middle Click
        if systemctl is-active bluetooth >/dev/null; then
            sudo systemctl stop bluetooth &
                notify-send -i $notif_icon "Stopping Bluetooth service"
        else
            sudo systemctl restart bluetooth &
                notify-send -i $notif_icon "Starting Bluetooth service"
        fi
        ;;
    3) # Right Click
        notify-send -i $notif_icon "Bluetooth Info" "$btinfo"
        ;;
    4) # Scroll Up
        ;;
    5) # Scroll Down
        ;;
esac

! systemctl is-active bluetooth >/dev/null && { echo " x" ; exit 1 ;}

if ! bluetoothctl info >/dev/null; then
    out="${out}X"
else
    for device in $connected_devices; do
        case "$(bluetoothctl info "$device" | awk '/Icon/ {print $2}')" in
            "audio-card")
                out="${out}"
                ;;
            "input-gaming")
                out="${out}"
                ;;
            *)
                out="${out}X"
                ;;
        esac
		battery_level=$(btbat "$device" | tr ' ' '\n' | tail -1)
		echo "$battery_level" | grep -q '%' && out="$out ($battery_level) "
    done
fi

out=$(echo "$out" | sed 's/ $//')

icon=

printf "\
<b><span foreground='$blockcolor' background='$color0'></span>\
<span foreground='$txtcolor' background='$blockcolor'> %s </span>\
<span foreground='$color0' background='$blockcolor'></span></b>\n" \
"$icon $out"
