#!/bin/sh
# shellcheck disable=1090,2154

. ~/.cache/wal/colors.sh
blockcolor=$color11
txtcolor=$color8

btinfo=$(bluetoothctl info)

case $BLOCK_BUTTON in
    # left click
	1) 
        bt-select
            ;;
    # middle click
	2) 
        if systemctl is-active bluetooth>/dev/null; then
            sudo systemctl stop bluetooth & notify-send "Stopping Bluetooth service"
        else
            sudo systemctl restart bluetooth & notify-send "Starting Bluetooth service"
        fi
            ;;
    # right click
    3) 
        notify-send "Bluetooth Info" "$btinfo"
            ;;
    # scroll up
	4) ;;
    # scroll down
	5) ;;
esac

if ! systemctl is-active bluetooth>/dev/null;then
    echo " x"
    exit
fi

case $(echo "$btinfo" | awk '/Icon/ {print $2}') in
    "audio-card")
        dev=
        ;;
    "input-gaming")
        dev=
        ;;
    *)
        dev=X
        ;;
esac

number_of_devs=$(bluetoothctl info | grep -c Device)

icon=

printf "\
<span foreground='$blockcolor' background='$color0'></span>\
<span foreground='$txtcolor' background='$blockcolor'>%s</span>\
<span foreground='$color0' background='$blockcolor'></span>\n" \
" $icon $number_of_devs:$dev "
# echo " $dev $(echo "$btinfo" | awk '/Name/ {$1="" ; print}')"
