#!/bin/sh
# shellcheck disable=1090,2154

. ~/.cache/wal/colors.sh

# icon=
icon= 

blockcolor=$color10
txtcolor=$color0

case $BLOCK_BUTTON in
    1) 
        notify-send -i ~/.local/bin/i3blocks/img/cpu.png \
            -h string:x-canonical-private-synchronous:i3bcpu \
            "My $(neofetch cpu | awk '{$1="";print}' | xargs)" "$(sensors | grep die -B2 -A6)" 
                    ;;
    3)
        notify-send -i ~/.local/bin/i3blocks/img/cpu.png \
            -h string:x-canonical-private-synchronous:i3bcpu \
            "$(neofetch cpu | awk '{$1="";print}' | awk -F@ '{print $1}' | xargs) Usage" "$(ps axch -o cmd:15,%cpu --sort=-%cpu | head)" 
                    ;;
            esac

threads=$(nproc)

usage=$(echo "$(ps aux | awk 'BEGIN {sum=0} {sum+=$3}; END {print sum}')/$threads" | bc)

clock=$(echo "$(lscpu | awk '/CPU MHz/ {print $3}')/1000" | bc -ql | cut -c-3)

command=$(sensors | awk '/die/ {print $2}')

printf "\
<span foreground='$blockcolor' background='$color0'></span>\
<span foreground='$txtcolor' background='$blockcolor'> %s </span>\
<span foreground='$color0' background='$blockcolor'></span>\n" \
"$icon $((usage))% ${clock}GHz ${command}"
