#!/bin/sh

case $BLOCK_BUTTON in
	1) notify-send -i /dev/null "CPU hogs" "$(ps axch -o cmd:15,%cpu --sort=-%cpu | head)" ;;
	3) notify-send "CPU module" "- Shows CPU temperature.
- Click to show intensive processes.
- % is of single core." ;;
esac

threads="$(grep -c "^processor" /proc/cpuinfo)"

usage=$(echo "$(ps aux | awk 'BEGIN {sum=0} {sum+=$3}; END {print sum}')/$threads" | bc)

if [ $usage -ge 90 ] ; then
    icon="  "
elif [ $usage -ge 60 ] ; then
    icon="  "
elif [ $usage -ge 40 ] ; then
    icon="  "
elif [ $usage -ge 10 ] ; then
    icon="  "
else
    icon="  "
fi

command=$(sensors | awk '/^Tdie/ {print $2}')

echo "$icon  $command"
