#!/bin/sh

case $BLOCK_BUTTON in
    1) notify-send -i ~/.local/bin/i3blocks/img/cpu.png \
        "My $(neofetch cpu | awk '{$1="";print}' | xargs)" "$(sensors | grep die -B2 -A6)" ;;
	3) notify-send -i /dev/null "CPU hogs" "$(ps axch -o cmd:15,%cpu --sort=-%cpu | head)" ;;
esac

threads="$(nproc)"

usage=$(echo "$(ps aux | awk 'BEGIN {sum=0} {sum+=$3}; END {print sum}')/$threads" | bc)

icon=

clock=$(echo "$(lscpu | awk '/MHz/ {print $3}')/1000" | bc -ql | cut -c-3)

command=$(sensors | awk '/^Tdie/ {print $2}')

echo "$icon  $((usage))% ${clock}GHz ${command}"
