#!/bin/sh
# shellcheck disable=1090,2154

. ~/.cache/wal/colors.sh

icon=
drive=/home

blockcolor=$color13
txtcolor=$color0

case $BLOCK_BUTTON in
	1) 
        notify-send \
            -h string:x-canonical-private-synchronous:i3bdsk \
            "💽 Disk space" "$(df -hT -x tmpfs -x squashfs -x devtmpfs)" 
        ;;
    3) 
        notify-send \
            -h string:x-canonical-private-synchronous:i3bdsk \
            "Scanning $HOME..."
        notify-send \
            -h string:x-canonical-private-synchronous:i3bdsk \
            "💽 Home folder disk usage by folder" "$(sudo du -hs $HOME/* | sort -h)" 
        ;;
esac

command=$(df -h "$drive" | awk ' /[0-9]/ {print $3 "/" $2}')

printf "\
<span foreground='$blockcolor' background='$color0'></span>\
<span foreground='$txtcolor' background='$blockcolor'>%s</span>\
<span foreground='$color0' background='$blockcolor'></span>\n" \
" $icon $command "
