#!/bin/sh
# shellcheck disable=1090,2154

. ~/.cache/wal/colors.sh

blockcolor=$color3
txtcolor=$color0

label=

if [ "$WAYLAND_DISPLAY" ]; then
	case $BLOCK_BUTTON in
		1) # Left Click
			xkblayout-state set +1
			;;
		2) # Middle Click
			xkblayout-state set +1
			;;
		3) # Right Click
			xkblayout-state set +1
			;;
		4) # Scroll Up
			xkblayout-state set +1
			;;
		5) # Scroll Down
			xkblayout-state set -1
			;;
	esac

	current_lang=$(swaymsg -t get_inputs | grep "xkb_active_layout_name" | uniq | awk -F'"' '{print $4}')
	if [ "$current_lang" = "English (US)" ]; then
		icon=" "
		# icon=US
	else
		icon=" "
		# icon=ES
	fi
else
	case $BLOCK_BUTTON in
		1) # Left Click
			xkblayout-state set +1
			;;
		2) # Middle Click
			xkblayout-state set +1
			;;
		3) # Right Click
			xkblayout-state set +1
			;;
		4) # Scroll Up
			xkblayout-state set +1
			;;
		5) # Scroll Down
			xkblayout-state set -1
			;;
	esac

	current_lang=$(xkblayout-state print %n)
	if [ "$current_lang" = "English" ]; then
		icon=" "
		# icon=US
	else
		icon=" "
		# icon=ES
	fi
fi

printf "\
<b><span foreground='$blockcolor' background='$color0'></span>\
<span foreground='$txtcolor' background='$blockcolor'>%s</span>\
<span foreground='$color0' background='$blockcolor'></span></b>\n" \
" $label $icon"
