#!/bin/sh
# shellcheck disable=1090,2154

. ~/.cache/wal/colors.sh

blockcolor=$color11
txtcolor=$color8

case $BLOCK_BUTTON in
	1)
        xkblayout-state set +1
        ;;
    2)
        xkblayout-state set +1
        ;;
	3) 
        xkblayout-state set +1
        ;;
	4) 
        xkblayout-state set +1
        ;;
	5) 
        xkblayout-state set -1
        ;;
esac

current_lang=$(xkblayout-state print %n)
if [ "$current_lang" = "English" ];then
    icon=" "
    # icon=US
else
    icon=" "
    # icon=ES
fi

label=

printf "\
<span foreground='$blockcolor' background='$color0'></span>\
<span foreground='$txtcolor' background='$blockcolor'>%s</span>\
<span foreground='$color0' background='$blockcolor'></span>\n" \
" $label $icon"
