#!/bin/sh
# shellcheck disable=1090,2154

. ~/.cache/wal/colors.sh
blockcolor=$color11
txtcolor=$color0

case $BLOCK_BUTTON in
    1) # Left Click
        $TERMINAL --class float -e neomutt
        ;;
    2) # Middle Click
        systemctl --user restart mailsync
        ;;
    3) # Right Click
        mw -Y
        ;;
esac

if [ -f "/tmp/imapsyncicon_$USER" ]; then
    icon=
else
    icon=
fi

printf "\
<b><span foreground='$blockcolor' background='$color0'></span>\
<span foreground='$txtcolor' background='$blockcolor'> %s </span>\
<span foreground='$color0' background='$blockcolor'></span></b>\n" \
"$icon $(find ~/.local/share/mail/*/INBOX/new/* | wc -l)"
