#!/bin/sh
# shellcheck disable=1090,2154

. ~/.cache/wal/colors.sh

icon=

blockcolor=$color11
txtcolor=$color0

case $BLOCK_BUTTON in
    1) # Left Click
        notify-send \
            -i ~/.local/bin/i3blocks/img/ram.png \
            -h string:x-canonical-private-synchronous:i3bmem \
            "Memory usage" "$(ps axch -o cmd:15,%mem --sort=-%mem | head)"
                    ;;
            esac

command=$(free -h | awk '/Mem/ {print $3 "/" $2}')

printf "\
<b><span foreground='$blockcolor' background='$color0'></span>\
<span foreground='$txtcolor' background='$blockcolor'>%s</span>\
<span foreground='$color0' background='$blockcolor'></span></b>\n" \
" $icon $command "
