#!/bin/sh

. ~/.cache/wal/colors.sh

icon=

case $BLOCK_BUTTON in
    1)
        playerctl previous
        ;;
    2)
        playerctl play-pause
        ;;
    3)
        playerctl next
        ;;
    4)
        playerctl position 5+
        ;;
    5)
        playerctl position 5-
        ;;
esac

if [ "$(playerctl -p mpd status)" = "Playing" ]; then
    artist="$(playerctl -p mpd metadata artist)"
    title="$(playerctl -p mpd metadata title)"
elif [ "$(playerctl -p spotify status)" = "Playing" ]; then
    artist="$(playerctl -p spotify metadata artist)"
    title="$(playerctl -p spotify metadata title)"
elif [ "$(playerctl -p mpv status)" = "Playing" ]; then
    artist="$(playerctl -p mpv metadata artist)"
    title="$(playerctl -p mpv metadata title)"
else
    artist="$(playerctl metadata artist)"
    title="$(playerctl metadata title)"
fi

# i3blocks doesn't seem to like ampersands
if echo "$artist" | grep -q '&';then
    artist=$(echo "$title" | sed 's/&/and/')
elif echo "$title" | grep -q '&';then
    title=$(echo "$title" | sed 's/&/and/')
fi

if [ -z "$artist" ]; then
    icon= 
    printf "%s  <span color='%s'>%s</span>\n" \
        "$icon" "$color13" "$title"
else
    printf "%s  <span color='%s'>%s</span> - <span color='%s'>%s</span>\n" \
        "$icon" "$color14" "$artist" "$color13" "$title"
fi

