#!/bin/sh

icon=

case $BLOCK_BUTTON in
    1)
        playerctl previous
        ;;
    2)
        playerctl play-pause
        ;;
    3)
        playerctl next
        ;;
    4)
        playerctl position 5+
        ;;
    5)
        playerctl position 5-
        ;;
esac

if [ "$(playerctl -p mpd status)" = "Playing" ]; then
  current_media="$(playerctl -p mpd metadata artist) - $(playerctl -p mpd metadata title)"
elif [ "$(playerctl -p spotify status)" = "Playing" ]; then
    current_media="$(playerctl -p spotify metadata artist) - $(playerctl -p spotify metadata title)"
elif [ "$(playerctl -p mpv status)" = "Playing" ]; then
    current_media="$(playerctl -p mpv metadata artist) - $(playerctl -p mpv metadata title)"
else
    current_media="$(playerctl metadata artist) - $(playerctl metadata title)"
fi

echo "$icon  $current_media"
