#!/bin/sh

case $BLOCK_BUTTON in
	1) # Left Click
        $TERMINAL --class float -e nmtui
        ;;
    2) # Middle Click
        ;;
	3) # Right Click
        ;;
esac

[ "$(cat /sys/class/net/w*/operstate)" = 'down' ] && wifiicon="📡"

[ -z "${wifiicon+var}" ] && wifiicon=$(grep "^\s*w" /proc/net/wireless | awk '{ print "📶", int($3 * 100 / 70) "%" }')

printf "%s %s\n" "$wifiicon" "$(cat /sys/class/net/e*/operstate | sed "s/down/❎/;s/up/🌐/")"
