#!/bin/sh
# shellcheck disable=1090,2154

label=

. ~/.cache/wal/colors.sh
blockcolor=$color9
txtcolor=$color0

case $BLOCK_BUTTON in
    1) # Left Click
        $TERMINAL --class float -e newsboat
        ;;
    2) # Middle Click
        systemctl --user restart nbupdate
        ;;
    3) # Right Click
        ;;
esac

[ ! -f ~/.local/share/newsboat/cache.db.lock ] &&
    newsboat -x print-unread | awk '{print $1}' > ~/.local/share/newsboat/unread

if [ -z "$(cat ~/.local/share/newsboat/unread)" ]; then
    if [ -f /tmp/nbupdate ]; then
        command=""
    else
        command=""
    fi
else
    if [ -f /tmp/nbupdate ]; then
        command="$(cat ~/.local/share/newsboat/unread) "
    else
        command="$(cat ~/.local/share/newsboat/unread)"
    fi
fi

printf "\
<b><span foreground='$blockcolor' background='$color0'></span>\
<span foreground='$txtcolor' background='$blockcolor'> %s </span>\
<span foreground='$color0' background='$blockcolor'></span></b>\n" \
"$label $command"
