#!/bin/sh
# shellcheck disable=1090,2154

label=

. ~/.cache/wal/colors.sh
blockcolor=$color9
txtcolor=$color0

TMUX_NEWS_WINDOW_NAME=" "

case $BLOCK_BUTTON in
    1) 
        tmux selectw -t"$TMUX_NEWS_WINDOW_NAME"
        ;;
    2)
        systemctl --user restart nbupdate 
        ;;
    3);;
esac

if [ ! -f ~/.local/share/newsboat/cache.db.lock ]; then
    newsboat -x print-unread | awk '{print $1}' > ~/.local/share/newsboat/unread
fi

if [ -z "$(cat ~/.local/share/newsboat/unread)" ]; then
    if [ -f /tmp/nbupdate ]; then
        command=""
    else
        command=""
    fi
else
    if [ -f /tmp/nbupdate ]; then
        command="$(cat ~/.local/share/newsboat/unread)  "
    else
        command="$(cat ~/.local/share/newsboat/unread)"
    fi
fi

printf "\
<span foreground='$blockcolor' background='$color0'></span>\
<span foreground='$txtcolor' background='$blockcolor'> %s </span>\
<span foreground='$color0' background='$blockcolor'></span>\n" \
"$label $command"
