#!/bin/sh
# shellcheck disable=1090,2154

. ~/.cache/wal/colors.sh
blockcolor=$color14
txtcolor=$color0

case $BLOCK_BUTTON in
    1) # Left Click
        notify-send "It is currently $(date +%X) on $(date +%A), $(date +%B%d), $(date +%Y)"
        ;;
    2) # Middle Click
        systemctl --user restart vdirsyncer
        ;;
    3) # Right Click
        notify-send "Upcoming Events" "$(khal list --format '{calendar} {start-time} {title}' today tomorrow)"
        ;;
    4) # Scroll Up
        notify-send "Upcoming Events" "$(khal list --format '{calendar} {start-time} {title}' today tomorrow)"
        ;;
    5) # Scroll Down
        notify-send "Upcoming Events" "$(khal list --format '{calendar} {start-time} {title}' today tomorrow)"
        ;;
esac

if [ -f /tmp/calsync ]; then
    label=""
else
    label=""
fi

printf "\
<b><span foreground='$blockcolor' background='$color0'></span>\
<span foreground='$txtcolor' background='$blockcolor'>%s</span></b>\n" \
" $label $(date '+%H%M/%S %m/%d/%Y') "
