#!/bin/sh
# shellcheck disable=1090,2154

. ~/.cache/wal/colors.sh
blockcolor=$color9
txtcolor=$color0

case $BLOCK_BUTTON in
    # left click
	1) 
    tmux selectw -tneomutt & 
    ;;
    # middle click
	2) 
    systemctl --user restart vdirsyncer 
    ;;
    # scroll up
	4) 
    notify-send "Upcoming Events" "$(khal list --format '{calendar} {start-time} {title}' today tomorrow)" 
    ;;
    # scroll down
	5) 
    notify-send "Upcoming Events" "$(khal list --format '{calendar} {start-time} {title}' today tomorrow)" 
    ;;
    # right click
	3) 
    notify-send "Upcoming Events" "$(khal list --format '{calendar} {start-time} {title}' today tomorrow)" 
    ;;
esac

label=

# if [ -f /tmp/calsync ]; then
#     echo "  $(date '+%H%M/%S %m/%d/%Y') 🔃"
# else
#     echo "  $(date '+%H%M/%S %m/%d/%Y')"
# fi

printf "\
<span foreground='$blockcolor' background='$color0'></span>\
<span foreground='$txtcolor' background='$blockcolor'>%s</span>\n" \
" $label $(date '+%H%M/%S %m/%d/%Y') "
