#!/bin/sh

togglepavu(){
    if pgrep pavucontrol; then
        killall -9 pavucontrol
    else
        setsid pavucontrol
    fi
}

case $BLOCK_BUTTON in
    # Left Click
	1) togglepavu ;;
    # Middle Click
	2) pamixer --toggle-mute ;;
    # Right Click
	3) killall -9 pavucontrol ;;
    # Scroll Up
	4) pamixer -i 5 ;;
    # Scroll Down
	5) pamixer -d 5 ;;
    # Backward Button
    8) ;;
    # Forward Button
    9) ;;
esac

[ "$(pamixer --get-mute)" = "true" ] && printf "🔇\\n" && exit

vol=$(pamixer --get-volume)

if [ "$vol" -gt "70" ]; then
	icon="🔊"
elif [ "$vol" -lt "30" ]; then
	icon="🔈"
else
	icon="🔉"
fi

printf "%s %s%%\\n" "$icon" "$vol"
