#!/bin/sh

case $BLOCK_BUTTON in
    1) 
        sudo systemctl restart mullvad-daemon
        ;;
    2) 
        sudo systemctl restart mullvad-daemon
        ;;
	3) 
        sudo systemctl restart mullvad-daemon
        ;;
esac

if [ "$(curl -s am.i.mullvad.net/connected | awk '{print $3}')" = not ]
then
    echo 'no mole'
elif [ "$(curl -s am.i.mullvad.net/connected | awk '{print $3}')" = connected ]
then
    echo mole
else
    echo X
fi
